apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  namespace: argocd-python
  labels:
    app: regapp 
spec:
  selector:
    app: regapp 

  ports:
    - port: 8080
      targetPort: 9099

  type: LoadBalancer
