name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: dilip433/dilip0110
      VERSION: v1.${{ github.run_number }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Unit Test
      run: mvn test

    - name: Integration Test
      run: mvn verify -DskipUnitTests

    - name: Maven Build
      run: mvn clean install

    - name: Upload JAR to Nexus
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        curl -v -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file target/Uber.jar \
          http://13.201.34.81:8081/repository/dilip/com/example/springboot/$VERSION/springboot-$VERSION.jar

    - name: Build Docker Image
      run: |
        docker build -t $IMAGE_NAME:${{ env.VERSION }} .
        docker tag $IMAGE_NAME:${{ env.VERSION }} $IMAGE_NAME:latest

    - name: Push Docker Image to Docker Hub
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login -u dilip433 --password-stdin
        docker push $IMAGE_NAME:${{ env.VERSION }}
        docker push $IMAGE_NAME:latest
